# Dependencies
markdown:         kramdown
highlighter:      rouge
plugins:          [jekyll-paginate]

# Permalinks
permalink:        pretty

# Setup
title:            Hyde
description:      'A brazen two-column <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that pairs a prominent sidebar with uncomplicated content. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:              https://jacob.moorman.me/hyde
baseurl:          "/hyde"

author:
  name:           'Jacob Moorman'
  url:            https://jacob.moorman.me/

# Blog configuration
has_blog:         True
paginate:         1
paginate_path:    "/blog/page:num/"
blog_url:        "/blog/"

# Configure prose
prose:
  metadata:
    _posts:
      - name: "title"
        field:
          element: "text"
          label: "title"
      - name: "layout"
        field:
          element: "hidden"
          value: "post"